# Generated by Django 2.2.12 on 2020-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='GET', max_length=16)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'requests',
                'ordering': ['time'],
            },
        ),
    ]
